// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PMQ.GerenciamentoTarefas.Infra.Data.Context;

#nullable disable

namespace PMQ.GerenciamentoTarefas.Infra.Data.Migrations
{
    [DbContext(typeof(TarefaContext))]
    [Migration("20240204202602_RemovidoColunaDescricaoTabelaEtiqueta")]
    partial class RemovidoColunaDescricaoTabelaEtiqueta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMQ.GerenciamentoTarefas.Domain.Entities.Tarefas.Etiqueta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("ETIQUETA", (string)null);
                });

            modelBuilder.Entity("PMQ.GerenciamentoTarefas.Domain.Entities.Tarefas.Tarefa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("EtiquetasId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ETIQUETAID");

                    b.Property<int>("Prioridade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRIORIDADE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetasId");

                    b.ToTable("TAREFA", (string)null);
                });

            modelBuilder.Entity("PMQ.GerenciamentoTarefas.Domain.Entities.Tarefas.Tarefa", b =>
                {
                    b.HasOne("PMQ.GerenciamentoTarefas.Domain.Entities.Tarefas.Etiqueta", "Etiquetas")
                        .WithMany()
                        .HasForeignKey("EtiquetasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Etiquetas");
                });
#pragma warning restore 612, 618
        }
    }
}
